### ISSUE TITLE
Cython Error While Installing

### ISSUE THREAD

**Issue by EggyLv999** [clab/dynet#1035]
I'm having trouble with pip install dynet, off the master branch. I can get it to work in another singularity environment, but for the particular one I'm trying to get it to work on, I get a Cython 0.27 error message. Any ideas? For tir users, this is the new singularity image that was just added to the cluster. @neubig  

```INFO:root:Building Cython extensions...
    INFO:root:INCLUDE_DIRS='/tmp/pip-WtB3dc-build /tmp/pip-WtB3dc-build/build/py2.7u-64bit/eigen/eigen-eigen-699b6595fc47'
    INFO:root:LIBRARIES='dynet cublas'
    INFO:root:LIBRARY_DIRS='. /opt/cuda-8.0/lib64 /tmp/pip-WtB3dc-build/build/py2.7u-64bit/dynet/'
    INFO:root:COMPILER_ARGS='-std=c++11 -Wno-unused-function'
    INFO:root:EXTRA_LINK_ARGS="-Wl,-rpath='/home/edgarc/miniconda2/lib/',--no-as-needed"
    INFO:root:RUNTIME_LIB_DIRS='/tmp/pip-WtB3dc-build/build/py2.7u-64bit/dynet/ /home/edgarc/miniconda2/lib/'
    cythoning /tmp/pip-WtB3dc-build/build/py2.7u-64bit/python/_dynet.pyx to /tmp/pip-WtB3dc-build/build/py2.7u-64bit/python/_dynet.cpp
    Traceback (most recent call last):
      File "/tmp/pip-WtB3dc-build/setup.py", line 373, in <module>
        data_files=[("../..", DATA_FILES)],
      File "/home/edgarc/miniconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/edgarc/miniconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/edgarc/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-WtB3dc-build/setup.py", line 318, in run
        _build_ext.run(self)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/edgarc/miniconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        ext.sources = self.cython_sources(ext.sources, ext)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
        full_module_name=module_name)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 693, in compile
        return compile_single(source, options, full_module_name)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 643, in compile_single
        return run_pipeline(source, options, full_module_name)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
        err, enddata = Pipeline.run_pipeline(pipeline, source)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
        data = run(phase, data)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
        return phase(data)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
        module_node.process_implementation(options, result)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 141, in process_implementation
        self.generate_c_code(env, options, result)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 371, in generate_c_code
        self.body.generate_function_definitions(env, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 4719, in generate_function_definitions
        self.body.generate_function_definitions(self.scope, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 3109, in generate_function_definitions
        FuncDefNode.generate_function_definitions(self, env, code)
      File "/home/edgarc/.local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 1809, in generate_function_definitions
        lenv.generate_library_function_declarations(code)
    AttributeError: 'LocalScope' object has no attribute 'generate_library_function_declarations'
    python/CMakeFiles/pydynet.dir/build.make:64: recipe for target 'python/timestamp' failed
    make[2]: *** [python/timestamp] Error 1
    CMakeFiles/Makefile2:173: recipe for target 'python/CMakeFiles/pydynet.dir/all' failed
    make[1]: *** [python/CMakeFiles/pydynet.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    error: /usr/bin/make -j 32```

Full logs: https://pastebin.com/yWiuergd

**Comment by neubig** [comment]
I'm using Anaconda from a clean environment and did the following (from within singularity):

    conda create --name python3 python=3 cython numpy
    source activate python3
    BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet

and

    conda create --name python2 python=2 cython numpy
    source activate python2
    BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet

I confirmed that both worked. Could you try installing with Anaconda using these commands?

**Comment by EggyLv999** [comment]
After all the work, I still get

```
(python2) Singularity ubuntu-16.04-lts_tensorflow-1.4.0_cudnn-8.0-v6.0.img:~> python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import dynet_config
>>> dynet_config.set_gpu()
>>> import dynet
[dynet] initializing CUDA
CUDA failure in cudaGetDeviceCount(&nDevices)
CUDA driver version is insufficient for CUDA runtime version
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaGetDeviceCount(&nDevices)
Aborted
```

Using the newest singularity version and a clean install of anaconda. Any ideas on how to diagnose this? This is all I have right now: 

```
edgarc@compute-0-17:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  381.09  Thu Mar 30 20:07:40 PDT 2017
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
```

**Comment by neubig** [comment]
This sounds like it's an environment issue as opposed to a DyNet issue, so maybe we can work this out via email.
