### ISSUE TITLE
minor bug of transpose?

### ISSUE THREAD

**Issue by duyvuleo** [clab/dynet#1104]
Hi,

I experienced the following behaviour of transpose operator:

```
import dynet as dy
mod = dy.Model()
px = mod.add_parameters((128,1))
ix = dy.parameter(px)
ix_mean = dy.mean_dim(ix, {0}, True)
```

I got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_dynet.pyx", line 3223, in _dynet.mean_dim
TypeError: mean_dim() takes at least 3 positional arguments (2 given)
```

I understand that ix_mean in this case has dimension (1,1) and transpose should work (though it does nothing). 

I think the dim_forward function should be corrected as follows:

```
Dim Transpose::dim_forward(const vector<Dim>& xs) const {
  DYNET_ARG_CHECK(xs.size() == 1, "Bad arguments to Transpose: " << xs);
  DYNET_ARG_CHECK(xs[0].nd == dims.size() || xs[0].num_nonone_dims() == 1 || xs[0].nd == 1, "Dimensions passed to transpose (" << dims.size() << ") must be equal to dimensions in input tensor (" << xs[0].nd << ')');
  Dim ret(xs[0]);
  ret.nd = dims.size();
  for(size_t i = 0; i < dims.size(); ++i)
    ret.d[i] = xs[0][dims[i]];
  return ret;
}
```

How do you think? I will do a PR. Thanks!

**Comment by neubig** [comment]
I think this should be corrected, but what is the behavior of the above function when we pass in a vector of dimension {10}? The desired behavior is that it should output a row vector {1,10}. I think that's what it used to do, but perhaps a recent PR broke this?

**Comment by duyvuleo** [comment]
>
> but what is the behavior of the above function when we pass in a vector of
> dimension {10}? The desired behavior is that it should output a row vector
> {1,10}.


The behaviour is normal. If we pass in a vector of dim (10,), it will
output a row vector (1, 10).

But, in some cases, it will be *incorrect* if we pass in a vector of dim
(1,).

--
Cheers,
Vu
