### ISSUE TITLE
dynet installation issue in python3.6.3 and windows10

### ISSUE THREAD

**Issue by jenlindadsouza** [clab/dynet#1165]
Request help with the installation. Please see the error log copy-pasted below. Thanks.

C:\WINDOWS\system32>pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to c:\users\jen\appdata\local\temp\pip-build-5vgxj9tl\dynet
Requirement already satisfied: cython in c:\users\jen\appdata\local\programs\python\python36\lib\site-packages (from dynet)
Requirement already satisfied: numpy in c:\users\jen\appdata\local\programs\python\python36\lib\site-packages (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... error
    Complete output from command c:\users\jen\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jen\\AppData\\Local\\Temp\\pip-build-5vgxj9tl\\dynet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jen\AppData\Local\Temp\pip-_fhz1t5i-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 209, in run
        log.info("CMAKE_PATH=%r" % CMAKE_PATH)
    Message: "CMAKE_PATH='F:\\\\Octave-4.2.1\\\\bin\\\\cmake.exe'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 210, in run
        log.info("MAKE_PATH=%r" % MAKE_PATH)
    Message: "MAKE_PATH='F:\\\\Octave-4.2.1\\\\bin\\\\make.exe'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 211, in run
        log.info("MAKE_FLAGS=%r" % " ".join(MAKE_FLAGS))
    Message: "MAKE_FLAGS='-j 4'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 212, in run
        log.info("EIGEN3_INCLUDE_DIR=%r" % EIGEN3_INCLUDE_DIR)
    Message: "EIGEN3_INCLUDE_DIR='C:\\\\Users\\\\Jen\\\\AppData\\\\Local\\\\Temp\\\\pip-build-5vgxj9tl\\\\dynet\\\\build\\\\py3.6-64bit\\\\eigen'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 213, in run
        log.info("EIGEN3_DOWNLOAD_URL=%r" % EIGEN3_DOWNLOAD_URL)
    Message: "EIGEN3_DOWNLOAD_URL='https://bitbucket.org/eigen/eigen/get/699b6595fc47.zip'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 214, in run
        log.info("CC_PATH=%r" % CC_PATH)
    Message: "CC_PATH='F:\\\\Octave-4.2.1\\\\bin\\\\gcc.exe'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 215, in run
        log.info("CXX_PATH=%r" % CXX_PATH)
    Message: "CXX_PATH='F:\\\\Octave-4.2.1\\\\bin\\\\g++.exe'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 216, in run
        log.info("SCRIPT_DIR=%r" % SCRIPT_DIR)
    Message: "SCRIPT_DIR='C:\\\\Users\\\\Jen\\\\AppData\\\\Local\\\\Temp\\\\pip-build-5vgxj9tl\\\\dynet'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 217, in run
        log.info("BUILD_DIR=%r" % BUILD_DIR)
    Message: "BUILD_DIR='C:\\\\Users\\\\Jen\\\\AppData\\\\Local\\\\Temp\\\\pip-build-5vgxj9tl\\\\dynet\\\\build\\\\py3.6-64bit'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 218, in run
        log.info("INSTALL_PREFIX=%r" % INSTALL_PREFIX)
    Message: "INSTALL_PREFIX='c:\\\\users\\\\jen\\\\appdata\\\\local\\\\programs\\\\python\\\\python36\\\\Lib\\\\site-packages\\\\..\\\\..\\\\..'"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 219, in run
        log.info("PYTHON=%r" % PYTHON)
    Message: "PYTHON='c:\\\\users\\\\jen\\\\appdata\\\\local\\\\programs\\\\python\\\\python36\\\\python.exe'"
    Arguments: ()
    cmake version 3.7.1

    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    g++.exe (GCC) 4.9.4
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 238, in run
        log.info("Creating build directory " + BUILD_DIR)
    Message: 'Creating build directory C:\\Users\\Jen\\AppData\\Local\\Temp\\pip-build-5vgxj9tl\\dynet\\build\\py3.6-64bit'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 252, in run
        log.info("Fetching Eigen...")
    Message: 'Fetching Eigen...'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 254, in run
        log.info("Unpacking Eigen...")
    Message: 'Unpacking Eigen...'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "c:\users\jen\appdata\local\programs\python\python36\lib\logging\__init__.py", line 994, in emit
        stream.write(msg)
    ValueError: underlying buffer has been detached
    Call stack:
      File "<string>", line 1, in <module>
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 399, in <module>
        data_files=[(os.path.join("..", ".."), DATA_FILES)],
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\jen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\setup.py", line 283, in run
        log.info("Configuring...")
    Message: 'Configuring...'
    Arguments: ()
    -- Building for: NMake Makefiles
    -- The C compiler identification is GNU 4.9.4
    -- The CXX compiler identification is GNU 4.9.4
    -- Check for working C compiler: F:/Octave-4.2.1/bin/gcc.exe
    CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "cmTC_b2d50\fast"
    -- Check for working C compiler: F:/Octave-4.2.1/bin/gcc.exe -- broken
    CMake Error at F:/Octave-4.2.1/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
      The C compiler "F:/Octave-4.2.1/bin/gcc.exe" is not able to compile a
      simple test program.

      It fails with the following output:

       Change Dir: C:/Users/Jen/AppData/Local/Temp/pip-build-5vgxj9tl/dynet/build/py3.6-64bit/CMakeFiles/CMakeTmp

      Run Build Command:"nmake" "/NOLOGO" "cmTC_b2d50\fast"

      Generator: execution of make failed.  Make command was: "nmake" "/NOLOGO"
      "cmTC_b2d50\fast"

      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:1 (project)

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Jen/AppData/Local/Temp/pip-build-5vgxj9tl/dynet/build/py3.6-64bit/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Jen/AppData/Local/Temp/pip-build-5vgxj9tl/dynet/build/py3.6-64bit/CMakeFiles/CMakeError.log".
    error: F:\Octave-4.2.1\bin\cmake.exe C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet -DCMAKE_INSTALL_PREFIX='c:\\users\\jen\\appdata\\local\\programs\\python\\python36\\Lib\\site-packages\\..\\..\\..' -DEIGEN3_INCLUDE_DIR='C:\\Users\\Jen\\AppData\\Local\\Temp\\pip-build-5vgxj9tl\\dynet\\build\\py3.6-64bit\\eigen' -DPYTHON='c:\\users\\jen\\appdata\\local\\programs\\python\\python36\\python.exe'

    ----------------------------------------
Command "c:\users\jen\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jen\\AppData\\Local\\Temp\\pip-build-5vgxj9tl\\dynet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jen\AppData\Local\Temp\pip-_fhz1t5i-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Jen\AppData\Local\Temp\pip-build-5vgxj9tl\dynet\

**Comment by danielhers** [comment]
`The C compiler "F:/Octave-4.2.1/bin/gcc.exe" is not able to compile a simple test program.`

**Comment by neubig** [comment]
In other words, this seems like a problem with the environment itself. Unfortunately most of the developers aren't using Windows so it's a bit hard for us to debug/give advice, but if you figure something out please tell us!
