### ISSUE TITLE
Compilation errors (cudnn related)

### ISSUE THREAD

**Issue by ffancellu** [clab/dynet#1471]
Hi, 

I am having problems when installing dynet with GPU support. I am following the instructions for manual installation at: https://dynet.readthedocs.io/en/latest/python.html#installing-dynet-for-python

I am running `make -j 2` but I have noticed it keeps failing when calling the cudnn-ops.cu file.
Here is the installation log:
[log.txt](https://github.com/clab/dynet/files/2455576/log.txt)
Any ideas on what is going on?

**Comment by ffancellu** [comment]
Update:

Following this issue https://github.com/clab/dynet/issues/517
and running: `CUDNN_ROOT=/opt/cuDNN-5.1/ BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet` I was able to successfully install dynet
However, now when I launch it in python I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/inf.ed.ac.uk/group/project/DRTproject/git/scanner/dynet-env/lib/python2.7/site-packages/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: /afs/inf.ed.ac.uk/group/project/DRTproject/git/scanner/dynet-env/lib/python2.7/site-packages/../../../lib/libdynet.so: undefined symbol: cudnnSetPooling2dDescriptor
```
Any idea on how to solve this issue?

**Comment by pmichel31415** [comment]
Could it be that it linked to a different version of CUDNN (6.5 instead of 5.1)?
