### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by ryanzhumich** [clab/dynet#1503]
Hello,

I would like to use DyNet with GPU support and I've successfully installed

$ BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /tmp/pip-install-JaxIGT/dynet
Requirement already satisfied: cython in ./system/anaconda2/lib/python2.7/site-packages (from dynet) (0.25.2)
Requirement already satisfied: numpy in ./system/anaconda2/lib/python2.7/site-packages (from dynet) (1.15.0)
Building wheels for collected packages: dynet
  Running setup.py bdist_wheel for dynet ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-oRa8zR/wheels/9d/7c/54/a2d66acfb1330579b24afd1bb8bdadbb99c89a3379c274ff23
Successfully built dynet
Installing collected packages: dynet
Successfully installed dynet-0.0.0

However, the import dynet fails with

>>> import dynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/lily/rz268/system/anaconda2/lib/python2.7/site-packages/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: /home/lily/rz268/system/anaconda2/lib/libdynet.so: undefined symbol: cublasSgemmStridedBatched
>>>

Do you know what's the problem?

**Comment by FilippoC** [comment]
I am not a python user, but I don't think the pip installed version of dynet supports GPU: https://dynet.readthedocs.io/en/latest/python.html#installing-a-cutting-edge-and-or-gpu-version

**Comment by ryanzhumich** [comment]
@FilippoC Thank you. But it looks like we can use the following to install GPU dynet according to the doc?

BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet

**Comment by ljjb** [comment]
I'm having a very similar issue:

```
ImportError: /home/myuser/dynet-base/myenv/lib/python3.6/site-packages/dyNET-0.0.0-py3.6-linux-x86_64.egg/_dynet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5dynet19ParameterCollection17add_subcollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by ssdavidson** [comment]
I too am getting a similar error when I try to import dynet after building from source for GPU support in Ubuntu.

`ImportError: /home/samdavid/parsing/uuparser/dynet-base/dynet/build/dynet/libdynet.so: undefined symbol: curandGenerateNormal`

Does anyone know how to resolve this issue? The installation seems to have gone fine - it completed with no errors. But now I cannot import dynet.
