### ISSUE TITLE
Dynet does not work even after I re-install it

### ISSUE THREAD

**Issue by erelsgl** [clab/dynet#1519]
Today I tried to run a simple dynet program (that I ran several months ago with no problems), and got the following error when running from PyCharm:

    Traceback (most recent call last):
      File "/home/erelsgl/Dropbox/dicta/text-taggers/test_dynet.py", line 1, in <module>
        import dynet
      File "/usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5-linux-x86_64.egg/dynet.py", line 17, in <module>
        from _dynet import *
    ImportError: libdynet.so: cannot open shared object file: No such file or directory

Strangely, when I run the same program from the terminal with python3, I get:

    Traceback (most recent call last):
      File "test_dynet.py", line 2, in <module>
        import dynet
    ModuleNotFoundError: No module named 'dynet'

I get the same errors even with a minimal program that only contains the single line:

    import dynet

I tried to re-install dynet in several ways:

    $ sudo pip3 install dynet
    Requirement already satisfied: dynet in /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5-linux-x86_64.egg (0.0.0)
    Requirement already satisfied: cython in /usr/local/lib/python3.5/dist-packages (from dynet) (0.25.2)
    Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from dynet) (1.12.1)

and also:

    $ sudo -H pip3 install git+https://github.com/clab/dynet#egg=dynet
    Requirement already satisfied: dynet from git+https://github.com/clab/dynet#egg=dynet in /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5-linux-x86_64.egg (0.0.0)
    Requirement already satisfied: cython in /usr/local/lib/python3.5/dist-packages (from dynet) (0.25.2)
    Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from dynet) (1.12.1)
    
But the program still does not work... what can I do?

**Comment by Flamboyant0Anya** [comment]
Excuse me! Have you solved the problem now? I met almost the same prblem but the error info is "ImportError: libcurand.so.10: cannot open shared object file: No such file or directory". My friend said that it is because the cuda version does not match dynet version. However, we cannot choose dynet version... o(╥﹏╥)o

**Comment by erelsgl** [comment]
I do not remember.. I went to do other projects
