### ISSUE TITLE
Issues during installation starting with numpy

### ISSUE THREAD

**Issue by chaimmetzger** [clab/dynet#665]
chaim@chaim-Lenovo-ideapad-FLEX-5-1570:~$ pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /tmp/pip-build-oEjKBx/dynet
Requirement already satisfied: cython in ./.local/lib/python2.7/site-packages (from dynet)
Collecting numpy (from dynet)
  Using cached numpy-1.13.0-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy, dynet
Exception:
Traceback (most recent call last):
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/chaim/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/numpy-1.13.0.dist-info'

**Comment by pmichel31415** [comment]
Try using the `--user` option of pip or install with sudo maybe?

**Comment by chaimmetzger** [comment]
It worked! Thank you! Other issue that came up was that my computer trying
to use python 3.6 instead of python 2.7 both of which are now resolved.
