### ISSUE TITLE
Cublas Error for some GPU hardwares

### ISSUE THREAD

**Issue by Rachine** [clab/dynet#681]
Hi,

Using Dynet 2.0 in a conda env, with Python 3.5, compiled with CUDA 7.5
For the GPU Tesla P100, witness Cublas errors in the computations.

```
CUBLAS failure in cublasSgemm(dev.cublas_handle, CUBLAS_OP_N, CUBLAS_OP_N, y.d.rows(), y.d.cols() * y.d.batch_elems(), l.d.cols(), kSCALAR_ONE, l.v, l.d.rows(), r.v, r.d.rows(), acc_scalar, y.v, y.d.rows())
13
Traceback (most recent call last):
  File "cpu_vs_gpu.py", line 35, in <module>
    do_gpu()
  File "cpu_vs_gpu.py", line 26, in do_gpu
    z.value()
  File "_gdynet.pyx", line 1472, in _gdynet.Expression.value (_gdynet.cpp:29245)
  File "_gdynet.pyx", line 1486, in _gdynet.Expression.value (_gdynet.cpp:29078)
RuntimeError: cublasSgemm(dev.cublas_handle, CUBLAS_OP_N, CUBLAS_OP_N, y.d.rows(), y.d.cols() * y.d.batch_elems(), l.d.cols(), kSCALAR_ONE, l.v, l.d.rows(), r.v, r.d.rows(), acc_scalar, y.v, y.d.rows())
```

This error does not show up with the `xor.py` example. The error also appears with the `xmnt` wrapper around dynet.

There is no problem with GPU Tesla K80.

**Comment by Rachine** [comment]
No issue for training and testing on a GPU GeForce 840M also.

**Comment by Rachine** [comment]
Issue not happening anymore with current version of dynet, so closing this issue.
