### ISSUE TITLE
Missing GPU support message is cryptic

### ISSUE THREAD

**Issue by neubig** [clab/dynet#718]
$ python examples/python/xor.py --dynet-gpu
    Traceback (most recent call last):
      File "examples/python/xor.py", line 2, in <module>
        import dynet as dy
      File "/Users/neubig/work/dynet/build/python/dynet.py", line 9, in <module>
        from _gdynet import *
    ImportError: No module named _gdynet

It would be better if this said something like "DyNet was not installed with GPU support. Please see the installation instructions (link) for how to make it possible to use GPUs."

**Comment by neubig** [comment]
Actually, now it looks like we get a segmentation fault :(
