### ISSUE TITLE
pip install after build gives error in TypeError in setup.py:180 on Windows

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#830]
On trying to pip install dynet after building the solution, I get the following `TypeError message` which causes the install to fail. 

```
G:\Code\C++\dynet\build\python>python ..\..\setup.py EIGEN3_INCLUDE_DIR="G:\Code\C++\eigen" build --build-dir="G:\Code\C++\dynet\build" --skip-build install
running build
INFO:root:CMAKE_PATH=F:\Program Files\CMake\bin\cmake.exe
Traceback (most recent call last):
  File "..\..\setup.py", line 337, in <module>
    py_modules=["dynet", "dynet_viz", "dynet_config"],
  File "F:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "F:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "F:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "..\..\setup.py", line 180, in run
    log.info("MAKE_PATH=" + MAKE_PATH)
TypeError: must be str, not NoneType
```

A possible fix to all of these messages is to use the python string formatting function to create the log messages. I will send a pull request on this.

**Comment by napsternxg** [comment]
I also found some additional errors with the skip-build part not getting properly used. E.g. when supplying `--skip-build` flag all the build steps should be skipped and the items from the build directory should be used. However, that doesn't happen as the build_ext function still calls the build for extensions. 

I have made the proper changes and was able to install dynet on my system properly and was able to run it as well. 

I will send a pull request referring to this issue.
