### ISSUE TITLE
Update examples based on the latest API

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#832]
I tried running the cpu_vs_gpu.py example with dynet 2.0 and it gives the following error:

```
python cpu_vs_gpu.py
Process Process-1:
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
Process Process-2:
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Code\C++\dynet\examples\python\cpu_vs_gpu.py", line 7, in do_cpu
    import _dynet as C
Traceback (most recent call last):
ModuleNotFoundError: No module named '_dynet'
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Code\C++\dynet\examples\python\cpu_vs_gpu.py", line 22, in do_gpu
    import _dynet as G
ModuleNotFoundError: No module named '_dynet'
```

I think in the latest API there is no `_dynet` module instead `dynet_config()` should be used.

**Comment by xunzhang** [comment]
Hi, it should work. Maybe you still use the old install instruction, or use the cached CMake build folder? Please follow this [link](https://github.com/clab/dynet/blob/master/.travis.yml#L92) to do the final step of installation. To make sure, if you can also not do `import dynet_config`, I think that is the case. (I am quite sure it works in Linux, and I don't have a WINDOWS env though.)

To clarify the interface, `_dynet` module is a lower level interface which is not suggested to use, `cpu_vs_gpu.py` uses it since this script needs to be run on both the CPU and the GPU environment. The right interface is one of the `dynet_config` or the `command line options` interfaces.

**Comment by xunzhang** [comment]
Hi @napsternxg , could you please verify whether it is working or not now?

**Comment by napsternxg** [comment]
I will do it this week and update here.

**Comment by napsternxg** [comment]
I am unable to install dynet on my machine because of #962 , hence this might be delayed.

**Comment by neubig** [comment]
Closing due to inactivity and because this is probably fixed.
