### ISSUE TITLE
unable to load model with GRU

### ISSUE THREAD

**Issue by michaelcapizzi** [clab/dynet#849]
Hi all - 

But I am unable to `load` a `model` containing a `GRUBuilder` object:

```
import dynet_config
dynet_config.set_gpu()
dynet_config.set(mem=2048, requested_gpus=1)
import dynet as dy

model = dy.ParameterCollection()

builders = [
    dy.GRUBuilder(1, 10, 7, model),
    dy.GRUBuilder(1, 10, 7, model)
]

pV = model.add_parameters((7 * 2, 2))
pb = model.add_parameters(2)

E = model.add_lookup_parameters((5, 10))

dy.save(
    "/home/mcapizzi/Desktop/test_model_gru",
    builders + [pV, pb, E]
)

loaded_model = dy.ParameterCollection()

loaded_params = dy.load(
    "/home/mcapizzi/Desktop/test_model_gru",
    loaded_model
)

print(loaded_params)
```

results in ....

```
(sentence-segmentation) mcapizzi@nextiva-desktop:/media/mcapizzi/data/Github/sentence-segmentation/src/nn_scripts$ python gru_load.py 
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 3.34037/4.2331
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 148289666
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "gru_load.py", line 27, in <module>
    loaded_model
  File "_dynet.pyx", line 371, in _dynet.load (_dynet.cpp:10688)
  File "_dynet.pyx", line 403, in _dynet.load (_dynet.cpp:10477)
  File "_dynet.pyx", line 310, in _dynet._load_one (_dynet.cpp:9960)
  File "_dynet.pyx", line 4155, in _dynet.GRUBuilder.from_spec (_dynet.cpp:56702)
TypeError: 'NoneType' object is not iterable
```

but if I change `GRUBuilder` to `LSTMBuilder`, it works.

```
import dynet_config
dynet_config.set_gpu()
dynet_config.set(mem=2048, requested_gpus=1)
import dynet as dy

model = dy.ParameterCollection()

builders = [
    dy.LSTMBuilder(1, 10, 7, model),
    dy.LSTMBuilder(1, 10, 7, model)
]

pV = model.add_parameters((7 * 2, 2))
pb = model.add_parameters(2)

E = model.add_lookup_parameters((5, 10))

dy.save(
    "/home/mcapizzi/Desktop/test_model_lstm",
    builders + [pV, pb, E]
)

loaded_model = dy.ParameterCollection()

loaded_params = dy.load(
    "/home/mcapizzi/Desktop/test_model_lstm",
    loaded_model
)

print(loaded_params)
```

```
(sentence-segmentation) mcapizzi@nextiva-desktop:/media/mcapizzi/data/Github/sentence-segmentation/src/nn_scripts$ python gru_load.py 
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 3.34037/4.2331
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 2120807314
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
[<_dynet.VanillaLSTMBuilder object at 0x7f508f7ad308>, <_dynet.VanillaLSTMBuilder object at 0x7f508f7ad360>, <_dynet.Parameters object at 0x7f508f7ad3b8>, <_dynet.Parameters object at 0x7f508f7ad410>, <_dynet.LookupParameters object at 0x7f508f7ae948>]
```

And as of Friday, September 1st, I have the most up-to-date to `dynet` code:
```
(sentence-segmentation) mcapizzi@nextiva-desktop:/media/mcapizzi/data/Github/dynet$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

**Comment by xunzhang** [comment]
Thanks for reporting. Fixed via https://github.com/clab/dynet/pull/851.
