### ISSUE TITLE
manual installation - done except "setup.py  build'

### ISSUE THREAD

**Issue by leejayyoon** [clab/dynet#912]
Hi, 

I am having errors  on the last line of command that I run for DyNet manual installation. I don't know what kind of implication this last step has, since the installation test code all seems to work fine. (at the end of the log, I've copied over what kind of tests I did to see if the installation was done correct way)

To summarize, my questions are

- Is the last step (setup.py build) necessary?
- If so, what are the implications?
- How do I overcome this error that I get on setup.py build ?

Here are detailed information of the system (OS, python version, complete commands & error logs):
**OS:**
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch:trialuse-4.1-amd64:trialuse-4.1-noarch
Distributor ID:	Springdale
Description:	Springdale Linux release 7.4 (Verona)
Release:	7.4
Codename:	Verona

**Python version:** 
Python 2.7.5

**GPU**:
Titan X 12G memory.

**Series of codes I ran:  (cmake runs if only I give the command an absolute path)**
    # Installing Python DyNet:

    pip install cython  # if you don't have it already.
    mkdir dynet-base
    cd dynet-base
    # getting dynet and eigen
    git clone https://github.com/clab/dynet.git
    hg clone https://bitbucket.org/eigen/eigen -r 346ecdb  # -r NUM specified a known working revision
    cd dynet
    mkdir build
    cd build
    # without GPU support (if you get an error that Eigen cannot be found, try using the full path to Eigen)
    cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python`
    # or with GPU support (if you get an error that Eigen cannot be found, try using the full path to Eigen)
    cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python` -DBACKEND=cuda

    make -j 2 # replace 2 with the number of available cores
    cd python
    python ../../setup.py build --build-dir=.. --skip-build install # add `--user` for a user-local install.
    
    # this should suffice, but on some systems you may need to add the following line to your
    # init files in order for the compiled .so files be accessible to Python.
    # /path/to/dynet/build/dynet is the location in which libdynet.dylib resides.
    export DYLD_LIBRARY_PATH=/path/to/dynet/build/dynet/:$DYLD_LIBRARY_PATH

**Among them, I got an error on** 
     python ../../setup.py build --build-dir=.. --skip-build install --user # add `--user` for a user-local   install.

(Note that, to prevent error, I used absolute path for my commands, but initially I used the given one above.)

**Actual copy of command & log**

jaylee@gpu2:~/dynet-base/dynet$ python setup.py build --build-dir=/zfsauton/home/jaylee/dynet-base/dynet/build --skip-build install --user
running build
INFO:root:CMAKE_PATH=/usr/bin/cmake
INFO:root:MAKE_PATH=/usr/bin/make
INFO:root:MAKE_FLAGS=-j 24
INFO:root:HG_PATH=/usr/bin/hg
INFO:root:EIGEN3_INCLUDE_DIR=/zfsauton/home/jaylee/dynet-base/eigen
INFO:root:CC_PATH=/usr/lib64/ccache/gcc
INFO:root:CXX_PATH=/usr/lib64/ccache/g++
INFO:root:SCRIPT_DIR=/zfsauton/home/jaylee/dynet-base/dynet
INFO:root:BUILD_DIR=/zfsauton/home/jaylee/dynet-base/dynet/build
INFO:root:INSTALL_PREFIX=/usr/lib/python2.7/site-packages/../../..
INFO:root:PYTHON=/usr/bin/python
cmake version 2.8.12.2
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

running build_py
INFO:root:Building Python files...
running build_ext
INFO:root:Building Cython extensions...
INFO:root:INCLUDE_DIRS=/zfsauton/home/jaylee/dynet-base/dynet /zfsauton/home/jaylee/dynet-base/eigen /zfsauton/home/jaylee/dynet-base/eigen
INFO:root:LIBRARIES=dynet
INFO:root:LIBRARY_DIRS=. /zfsauton/home/jaylee/dynet-base/dynet/build/dynet/ /zfsauton/home/jaylee/dynet-base/dynet/build/dynet/
INFO:root:COMPILER_ARGS=-std=c++11
INFO:root:EXTRA_LINK_ARGS=-Wl,-rpath=/usr/local/lib/,--no-as-needed
INFO:root:RUNTIME_LIB_DIRS=/zfsauton/home/jaylee/dynet-base/dynet/build/dynet/ /usr/local/lib/
skipping '_dynet.cpp' Cython extension (up-to-date)
INFO:root:Copying built extensions...
running install
running bdist_egg
running egg_info
creating dyNET.egg-info
writing requirements to dyNET.egg-info/requires.txt
writing dyNET.egg-info/PKG-INFO
writing top-level names to dyNET.egg-info/top_level.txt
writing dependency_links to dyNET.egg-info/dependency_links.txt
writing manifest file 'dyNET.egg-info/SOURCES.txt'
file dynet.py (for module dynet) not found
file dynet_viz.py (for module dynet_viz) not found
file dynet_config.py (for module dynet_config) not found
reading manifest file 'dyNET.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dyNET.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/dynet_config.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_dynet.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/dynet_viz.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/dynet.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/dynet_config.py to dynet_config.pyc
byte-compiling build/bdist.linux-x86_64/egg/dynet_viz.py to dynet_viz.pyc
byte-compiling build/bdist.linux-x86_64/egg/dynet.py to dynet.pyc
creating stub loader for _dynet.so
byte-compiling build/bdist.linux-x86_64/egg/_dynet.py to _dynet.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dyNET.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dyNET.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dyNET.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dyNET.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dyNET.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dyNET-0.0.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dyNET-0.0.0-py2.7-linux-x86_64.egg
Removing /zfsauton/home/jaylee/.local/lib/python2.7/site-packages/dyNET-0.0.0-py2.7-linux-x86_64.egg
Copying dyNET-0.0.0-py2.7-linux-x86_64.egg to /zfsauton/home/jaylee/.local/lib/python2.7/site-packages
dyNET 0.0.0 is already the active version in easy-install.pth

Installed /zfsauton/home/jaylee/.local/lib/python2.7/site-packages/dyNET-0.0.0-py2.7-linux-x86_64.egg
Traceback (most recent call last):
  File "setup.py", line 341, in <module>
    py_modules=["dynet", "dynet_viz", "dynet_config"],
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Tests I have done: (all of them works)**
import dynet as dy
print dy.__version__
pc = dy.ParameterCollection()

[dynet] random seed: 349867892
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
>>> print dy.__version__
2.0

cd $PATH_TO_DYNET
cd examples/python
python xor.py
python rnnlm.py rnnlm.py

import dynet_config
dynet_config.set_gpu()
import dynet
[dynet] initializing CUDA
Request for 0 GPUs ...
[dynet] random seed: 4252866291
[dynet] allocating memory: 512MB
[dynet] memory allocation done.

**Comment by leejayyoon** [comment]
I digged further, and realized that it was problem of setuptools. 

This resolved the issues: pip install --upgrade --user setuptools
