### ISSUE TITLE
train_imdb: coredump

### ISSUE THREAD

**Issue by stefan-it** [clab/dynet#951]
Hi dynet-users,

I'm trying train the imdb example with the following input data (small entry):

```text
5 ||| a traveller experiences strange paranormal activity in a room at an inn where he stops to stay the night . | clothes fly around , a chair vanishes and his boots walk off ; all to the consternation of the spooked out man . | this little comic short from georges méliès is a very early showcase for his cinematic trickery and visual invention . | just as significantly it illustrates his sense of humour . | méliès made many funny films which incredibly are still amusing even now , over a century down the line . | the effects remain impressive even though we all know how they are done . | there is always a loving care in méliès work . | this one is no exception and shows why he is the first cinematic genius .
```

I'm not quite 100% sure, if this is the correct input format, but I'm planning to write a small documentation for the `imdb` example.

Here's the output:

```bash
[stefan@arch-mse examples]$ ./train_imdb ~/imdb_dataset/imdb-train.txt ~/imdb_dataset/imdb-dev.txt
[dynet] random seed: 763958800
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Reading training data from /home/stefan/imdb_dataset/imdb-train.txt...
280593 lines, 3929753 sentences, 87596427 tokens, 115353 types
Labels: 10
Reading dev data from /home/stefan/imdb_dataset/imdb-dev.txt...
33793 lines, 475459 sentences, 10599895 tokens
Parameters will be written to: imdb_100_200_400_200-pid3185.params
**SHUFFLE
[lr=0.001 clips=20 updates=100]  E = 2.35599 ppl=10.5486 (acc=0.13) NORM: 350.165
[completed in 10731.7 ms]
[lr=0.001 clips=32 updates=100]  E = 2.42035 ppl=11.2498 (acc=0.15) NORM: 350.542
[completed in 11682.4 ms]
*** Error in `./train_imdb': corrupted size vs. prev_size: 0x0000558d99610720 ***
```

I'm using 6e1e9f496973c7f77d85aea44481e9a50c654249 of `dynet`, `eigen` 3.3.4, and GCC 7.2 on Arch Linux.

**Comment by stefan-it** [comment]
Another error message is:

```bash
*** Error in `./train_imdb': double free or corruption (out): 0x0000555661364c00 ***
```

**Comment by stefan-it** [comment]
Output from AddressSanitizer:

```bash
=================================================================
==4647==ERROR: AddressSanitizer: attempting double-free on 0x611003ac0400 in thread T0:
    #0 0x7fd16a92b711 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45
    #1 0x7fd169988ab0 in _mm_free /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include/mm_malloc.h:54
    #2 0x7fd169988e99 in dynet::CPUAllocator::free(void*) /mnt/Repositories/dynet/dynet/mem.cc:38
    #3 0x7fd169999ce4 in float dynet::ParameterCollectionStorage::gradient_l2_norm_dev<dynet::Device_CPU>(dynet::Device_CPU&) const /mnt/Repositories/dynet/dynet/model.cc:793
    #4 0x7fd1699941df in dynet::ParameterCollectionStorage::gradient_l2_norm() const /mnt/Repositories/dynet/dynet/model.cc:844
    #5 0x7fd169994375 in dynet::ParameterCollection::gradient_l2_norm() const /mnt/Repositories/dynet/dynet/model.cc:848
    #6 0x7fd16a22c6c5 in dynet::Trainer::clip_gradients() /mnt/Repositories/dynet/dynet/training.cc:60
    #7 0x7fd16a22ce76 in dynet::Trainer::update() /mnt/Repositories/dynet/dynet/training.cc:92
    #8 0x562bed6d22b1 in main /mnt/Repositories/dynet/examples/cpp/imdb/train_imdb.cc:282
    #9 0x7fd167f61f69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)
    #10 0x562bed6cfbd9 in _start (/mnt/Repositories/dynet/build/examples/train_imdb+0x1fbd9)

0x611003ac0400 is located 0 bytes inside of 168-byte region [0x611003ac0400,0x611003ac04a8)
freed by thread T0 here:
    #0 0x7fd16a92b711 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45
    #1 0x7fd169988ab0 in _mm_free /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include/mm_malloc.h:54
    #2 0x7fd169988e99 in dynet::CPUAllocator::free(void*) /mnt/Repositories/dynet/dynet/mem.cc:38
    #3 0x7fd16998dd65 in dynet::ParameterCollectionStorage::project_weights(float) /mnt/Repositories/dynet/dynet/model.cc:262
    #4 0x7fd16998ea4a in dynet::ParameterCollection::project_weights(float) /mnt/Repositories/dynet/dynet/model.cc:304
    #5 0x562bed6d24ae in main /mnt/Repositories/dynet/examples/cpp/imdb/train_imdb.cc:288
    #6 0x7fd167f61f69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)

previously allocated by thread T0 here:
    #0 0x7fd16a92c791 in __interceptor_posix_memalign /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:134
    #1 0x7fd169988a16 in _mm_malloc /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include/mm_malloc.h:45
    #2 0x7fd169988c26 in dynet::CPUAllocator::malloc(unsigned long) /mnt/Repositories/dynet/dynet/mem.cc:29
    #3 0x7fd169999d7d in float dynet::ParameterCollectionStorage::gradient_l2_norm_dev<dynet::Device_CPU>(dynet::Device_CPU&) const /mnt/Repositories/dynet/dynet/model.cc:795
    #4 0x7fd1699941df in dynet::ParameterCollectionStorage::gradient_l2_norm() const /mnt/Repositories/dynet/dynet/model.cc:844
    #5 0x7fd169994375 in dynet::ParameterCollection::gradient_l2_norm() const /mnt/Repositories/dynet/dynet/model.cc:848
    #6 0x7fd16a22c6c5 in dynet::Trainer::clip_gradients() /mnt/Repositories/dynet/dynet/training.cc:60
    #7 0x7fd16a22ce76 in dynet::Trainer::update() /mnt/Repositories/dynet/dynet/training.cc:92
    #8 0x562bed6d22b1 in main /mnt/Repositories/dynet/examples/cpp/imdb/train_imdb.cc:282
    #9 0x7fd167f61f69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)

SUMMARY: AddressSanitizer: double-free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45 in __interceptor_free
==4647==ABORTING
```
