### ISSUE TITLE
CPU memory allocation failed n=2097152000 align=32

### ISSUE THREAD

**Issue by xiaolongjean** [clab/dynet#983]
when I was running a programming with dynet, I met with the follwing problem:

**CPU memory allocation failed n=2097152000 align=32**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xx/桌面/new_project/src/word2vec2.py", line 483, in worker_train
    job_words = self._get_job_words(alpha, work, job, neu1)
  File "/home/xx/桌面/new_project/src/train.py", line 807, in _get_job_words
    x,y = self.train_gold_per_sentence(train_sentence, train_labels, alpha, work)
  File "/home/xx/桌面/new_project/src/train.py", line 496, in train_gold_per_sentence
    self.trainer.update()
  File "_dynet.pyx", line 5230, in _dynet.Trainer.update
  File "_dynet.pyx", line 5235, in _dynet.Trainer.update
**RuntimeError: CPU memory allocation failed**

It is "**RuntimeError: CPU memory allocation failed**" not "**Memeory Error**", and how to cope with the problem?

**Comment by xunzhang** [comment]
"CPU memory allocation failed" is RuntimeError in DyNet(https://github.com/clab/dynet/blob/master/dynet/except.h#L13). I think it should be out of memory(20GB) on your machine.
