### ISSUE TITLE
GLIBC_2.23 not found and Symbol not found

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#995]
after upgrading by using script like below,

```bash
export PATH_TO_DYNET=`realpath ~/usr/opt/dynet`
export PATH_TO_EIGEN=`realpath ~/usr/opt/eigne346ecdb/`
export LD_LIBRARY_PATH="${PATH_TO_DYNET}/build/dynet:${LD_LIBRARY_PATH}"

function upgrade_dynet() {
    PATH_TO_PYTHON=`which python3.6`
    pushd ${PATH_TO_DYNET}
    
    BRANCH=${1:-master}
    git stash
    git checkout $BRANCH
    git pull origin $BRANCH

    mkdir -p build
    pushd build
    cmake .. -DEIGEN3_INCLUDE_DIR=${PATH_TO_EIGEN} -DPYTHON=${PATH_TO_PYTHON}
    make -j 4

    pushd ${PATH_TO_DYNET}/build/python
    python3.6 ../../setup.py EIGEN3_INCLUDE_DIR=${PATH_TO_EIGEN} build --build-dir=.. --skip-build install
    popd
    popd
}
```

I got error like this on Ubuntu 16.04.3 LTS.

```python
Python 3.6.1 (default, Apr  4 2017, 23:52:48)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yiran/.local/lib/python3.6/site-packages/dyNET-0.0.0-py3.6-linux-x86_64.egg/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: /mnt/orange/brew/data/lib/libm.so.6: version `GLIBC_2.23' not found (required by /mnt/berry/home/yiran/usr/opt/dynet/build/dynet/libdynet.so)
```

and this on macOS High Sierra.

```python
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lambdell/Library/Python/3.6/lib/python/site-packages/dyNET-0.0.0-py3.6-macosx-10.6-intel.egg/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: dlopen(/Users/lambdell/Library/Python/3.6/lib/python/site-packages/dyNET-0.0.0-py3.6-macosx-10.6-intel.egg/_dynet.cpython-36m-darwin.so, 2): Symbol not found: __ZN5dynet10moment_dimERKNS_10ExpressionEjj
  Referenced from: /Users/lambdell/Library/Python/3.6/lib/python/site-packages/dyNET-0.0.0-py3.6-macosx-10.6-intel.egg/_dynet.cpython-36m-darwin.so
  Expected in: /Users/lambdell/tools/dynet/build/dynet/libdynet.dylib
 in /Users/lambdell/Library/Python/3.6/lib/python/site-packages/dyNET-0.0.0-py3.6-macosx-10.6-intel.egg/_dynet.cpython-36m-darwin.so
```

**Comment by speedcell4** [comment]
problem solved by degrading gcc

**Comment by git-junli** [comment]
@speedcell4 
Hi, I got the same error as you. 

`ImportError: /lib64/libm.so.6: version 'GLIBC_2.23' not found (required by dynet-base/dynet/build/dynet/libdynet.so)`

 I checked that there is a libm.so.6 in /lib64/, maybe it has a different version? But I don't have root privilege (I only have permission to $HOME), will degrading gcc work for me? And how to degrade gcc without root privilege?  

Any help will be appreciated !

**Comment by speedcell4** [comment]
I don't have root privilege neither, my compiled a gcc on my own $HOME and I mean I degrade that one.
I think you can find out which `libc.so` your gcc is actually using by `gcc -print-file-name=libc.so` and set `LIBRARAY_PATH` or something to there. by the way `ldd $HOME/dynet-base/dynet/build/dynet/libdynet.so`  shows you the `libc.so` that `dynet.so` linked to

**Comment by git-junli** [comment]
@speedcell4 
Thanks for your reply! Those commands are very useful !!!!
